export const pagesArray = [
  "Home v1",
  "Home v2",
  "Home v3",
  "About 1",
  "About 2",
  "Blog 1",
  "Blog 2",
  "Blog Single",
  "Contact",
  "Careers",
  "FAQ",
  "Privacy Policy",
  "Terms of Service",
  "Support",
  "Feedback",
];
export const utilityPagesArray = [
  "Help Center",
  "Documentation",
  "API Reference",
  "Developer Tools",
  "Community Forum",
  "Status Page",
  "License Agreement",
  "Cookie Policy",
  "Accessibility",
  "Sitemap",
  "Press",
  "Partners",
];
export const helpCenterV2Array = [
  "Getting Started",
  "FAQs",
  "Account Management",
  "Billing and Payments",
  "Troubleshooting",
  "Security & Privacy",
  "Contact Support",
  "Live Chat",
  "Submit a Ticket",
  "Feedback",
  "Terms of Service",
  "User Guide",
];
